"""
推送权限类型常量定义
"""

# 推送类型常量
NOTIFICATION_TYPE_REPORT_1 = "review1"        # 模板1推送
NOTIFICATION_TYPE_REPORT_5 = "review5"        # 模板5推送
NOTIFICATION_TYPE_WEEKLY_REPORT = "weekly_report"        # 周报推送
NOTIFICATION_TYPE_DAILY_REPORT = "daily_report"          # 日报推送
NOTIFICATION_TYPE_VISIT_RECORD = "visit_record"          # 拜访记录推送
NOTIFICATION_TYPE_LIST_VISIT_RECORDS = "list_visit_records"          # 查看拜访记录列表

# 所有推送类型列表
ALL_NOTIFICATION_TYPES = [
    NOTIFICATION_TYPE_REPORT_1,
    NOTIFICATION_TYPE_REPORT_5,
    NOTIFICATION_TYPE_WEEKLY_REPORT,
    NOTIFICATION_TYPE_DAILY_REPORT,
    NOTIFICATION_TYPE_VISIT_RECORD,
    NOTIFICATION_TYPE_LIST_VISIT_RECORDS,
]

# 推送类型描述
NOTIFICATION_TYPE_DESCRIPTIONS = {
    NOTIFICATION_TYPE_REPORT_1: "模板1推送",
    NOTIFICATION_TYPE_REPORT_5: "模板5推送",
    NOTIFICATION_TYPE_WEEKLY_REPORT: "周报推送",
    NOTIFICATION_TYPE_DAILY_REPORT: "日报推送",
    NOTIFICATION_TYPE_VISIT_RECORD: "拜访记录推送",
    NOTIFICATION_TYPE_LIST_VISIT_RECORDS: "查看拜访记录列表",
}

# 默认权限配置 - 可以根据角色设置默认权限
DEFAULT_PERMISSIONS = {
    "admin": ALL_NOTIFICATION_TYPES,  # 管理员拥有所有权限
    "extend_admin": [
        NOTIFICATION_TYPE_REPORT_1,
        NOTIFICATION_TYPE_REPORT_5,
        NOTIFICATION_TYPE_WEEKLY_REPORT,
        NOTIFICATION_TYPE_LIST_VISIT_RECORDS,
    ],
    "leader": [
        NOTIFICATION_TYPE_WEEKLY_REPORT,
        NOTIFICATION_TYPE_DAILY_REPORT,
        NOTIFICATION_TYPE_VISIT_RECORD,
    ],
    "sales": [
        NOTIFICATION_TYPE_DAILY_REPORT,
        NOTIFICATION_TYPE_VISIT_RECORD,
    ],
}
