name: aptsell

services:
  redis:
    image: registry.cn-beijing.aliyuncs.com/pingcap-ee/redis:6.0.16
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - /Users/gaona/redis-data:/data
    command: ["redis-server", "--loglevel", "warning"]

  auth:
    image: registry.cn-beijing.aliyuncs.com/aptsell/aptsell.ai-auth:rc0.0.1
    restart: always
    ports:
      - "8018:8018"
    volumes:
      - ./application.yml:/app/application.yml
    working_dir: /app
    command: ["java", "-jar", "aptsell.jar", "--spring.config.location=/app/application.yml"]
    depends_on:
      - redis

  backend:
    image: registry.cn-beijing.aliyuncs.com/aptsell/aptsell.ai-backend:0.1.2
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./data:/shared/data:
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"


  frontend:
    image: registry.cn-beijing.aliyuncs.com/aptsell/aptsell.ai-frontend:0.1.0
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      BASE_URL: http://backend
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"


  background:
    image: registry.cn-beijing.aliyuncs.com/aptsell/aptsell.ai-backend:0.1.2
    restart: always
    depends_on:
      - redis
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./data:/shared/data
    command: /usr/bin/supervisord
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"
