from typing import List, Optional
from datetime import datetime
from sqlalchemy import ForeignKey, Integer
from sqlmodel import Field, Column, DateTime, Relationship, SQLModel, Text

from app.models.crm_accounts import CRMAccount

class CRMOpportunity(SQLModel, table=True):
    class Config:
        orm_mode = True
        read_only = True
        
    """商机表"""
    id: Optional[int] = Field(default=None, primary_key=True)
    unique_id: Optional[str] = Field(nullable=True, max_length=255, description="唯一性ID（必填）")
    opportunity_name: Optional[str] = Field(nullable=True, max_length=255, description="商机名称（必填）")
    # primary_database: Optional[str] = Field(nullable=True, max_length=255, description="主要数据库")
    # primary_database_percentage: Optional[float] = Field(nullable=True, description="主要数据库占比（%）")
    # current_database_resource: Optional[str] = Field(nullable=True, max_length=255, description="主数据库当前所用资源")
    # current_database_pain_points: Optional[str] = Field(nullable=True, max_length=255, description="现用数据库痛点")
    # expected_launch_date: Optional[str] = Field(nullable=True, max_length=255, description="预计上线日期")
    # expected_closing_month: Optional[str] = Field(nullable=True, max_length=255, description="预计成交月")
    # service_amount_calculated: Optional[float] = Field(nullable=True, description="Service金额-计算")
    # current_year_subscription_forecast: Optional[float] = Field(nullable=True, description="当财年 Subscription 收入预测金额（不含税）")
    competitor_name: Optional[str] = Field(nullable=True, max_length=255, description="友商名称")
    # customer_journey_percentage: Optional[float] = Field(nullable=True, description="客户旅程（%）")
    # opportunity_level: Optional[str] = Field(nullable=True, max_length=255, description="商机2.0层级")
    # price_list_id: Optional[str] = Field(nullable=True, max_length=255, description="价目表_唯一性ID")
    # price_list: Optional[str] = Field(nullable=True, max_length=255, description="价目表")
    # service_days_type: Optional[str] = Field(nullable=True, max_length=255, description="人天服务类型")
    # cancellation_reason: Optional[str] = Field(nullable=True, max_length=255, description="取消原因")
    # is_slip_deal: Optional[str] = Field(nullable=True, max_length=255, description="是否为 slip deal")
    # forecast_amount: Optional[float] = Field(nullable=True, description="预测金额")
    # solution_owner_1: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案负责人-1")
    # unit: Optional[str] = Field(nullable=True, max_length=255, description="单位")
    # lifecycle_status: Optional[str] = Field(nullable=True, max_length=255, description="生命状态")
    # current_year_license_forecast: Optional[float] = Field(nullable=True, description="当财年 License 收入预测金额（不含税）")
    former_name: Optional[str] = Field(nullable=True, max_length=255, description="曾用名")
    partner_opportunity_filing_id_unique_id: Optional[str] = Field(nullable=True, max_length=255, description="合作伙伴商机报备编号_唯一性ID")
    partner_opportunity_filing_number: Optional[str] = Field(nullable=True, max_length=255, description="合作伙伴商机报备编号")
    # is_double_credit: Optional[str] = Field(nullable=True, max_length=255, description="Double credit or not")
    # confirmed_revenue_excl_tax: Optional[float] = Field(nullable=True, description="已确认收入金额(不含税)")
    # ma_acv: Optional[float] = Field(nullable=True, description="MA ACV")
    # service_acv: Optional[float] = Field(nullable=True, description="Service ACV")
    # data_volume: Optional[str] = Field(nullable=True, max_length=255, description="数据量")
    # expected_service_end_date: Optional[str] = Field(nullable=True, max_length=255, description="预计服务结束日期")
    # subscription_acv: Optional[float] = Field(nullable=True, description="Subscription ACV")
    filing_opportunity_number: Optional[str] = Field(nullable=True, max_length=255, description="报备商机编号")
    # license_amount_calculated: Optional[float] = Field(nullable=True, description="License金额-计算")
    # sales_log_details: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="当前详细状态及Close节奏(销售日志)")
    # estimated_solution_1_nodes: Optional[float] = Field(nullable=True, description="预估联合解决方案-1 节点数或vCPU数")
    # data_consolidation: Optional[str] = Field(nullable=True, max_length=255, description="Data Consolidation")
    # current_year_revenue_forecast: Optional[float] = Field(nullable=True, description="当财年收入预测金额（不含税）")
    call_high_notes: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="Call high 情况")
    # lock_status: Optional[str] = Field(nullable=True, max_length=255, description="锁定状态")
    # framework_agreement_type: Optional[str] = Field(nullable=True, max_length=255, description="框架协议商机类型")
    # is_key_deal: Optional[str] = Field(nullable=True, max_length=255, description="是否为 Key deals")
    department: Optional[str] = Field(nullable=True, max_length=255, description="归属部门")
    # estimated_solution_2_nodes: Optional[float] = Field(nullable=True, description="预估联合解决方案-2 节点数/ vCPU数")
    # estimated_total_project_nodes: Optional[float] = Field(nullable=True, description="预估整体项目节点数或vCPU数")
    # parent_opportunity_id: Optional[str] = Field(nullable=True, max_length=255, description="上级商机2.0_唯一性ID")
    # parent_opportunity: Optional[str] = Field(nullable=True, max_length=255, description="上级商机2.0")
    current_year_service_forecast: Optional[float] = Field(nullable=True, description="当财年 Service 收入预测金额（不含税）")
    # ma_amount_calculated: Optional[float] = Field(nullable=True, description="MA 金额-计算")
    # competitor_info: Optional[str] = Field(nullable=True, max_length=255, description="友商信息")
    # is_unified_generation: Optional[str] = Field(nullable=True, max_length=255, description="是否统一生成")
    customer_budget_status: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="客户预算情况")
    todo_and_followup: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="Todo & follow up")
    # license_acv: Optional[float] = Field(nullable=True, description="License ACV")
    # external_owner: Optional[str] = Field(nullable=True, max_length=255, description="外部负责人")
    # subscription_amount_calculated: Optional[float] = Field(nullable=True, description="Subscription 金额-计算")
    # current_year_ma_forecast: Optional[float] = Field(nullable=True, description="当财年 MA 收入预测金额（不含税）")
    is_framework_quote: Optional[str] = Field(nullable=True, max_length=255, description="是否框架协议报价商机")
    # data_volume_tb_gb: Optional[str] = Field(nullable=True, max_length=255, description="数据量（TB/GB）")
    customer_id: Optional[str] = Field(nullable=True, max_length=255, description="客户名称_唯一性ID（必填）")
    customer_name: Optional[str] = Field(nullable=True, max_length=255, description="客户名称（必填）")
    customer_type: Optional[str] = Field(nullable=True, max_length=255, description="客户属性")
    owner: Optional[str] = Field(nullable=True, max_length=255, description="负责人（必填）")
    customer_business_scenario: Optional[str] = Field(nullable=True, max_length=255, description="客户业务场景")
    forecast_type: Optional[str] = Field(nullable=True, max_length=255, description="预测类型")
    # timing_risk: Optional[str] = Field(nullable=True, max_length=255, description="Timing 风险")
    estimated_tcv: Optional[int] = Field(nullable=True, description="预估 TCV")
    estimated_acv: Optional[int] = Field(nullable=True, description="预估 ACV")
    expected_closing_date: Optional[str] = Field(nullable=True, max_length=255, description="预计成交日期")
    expected_closing_quarter: Optional[str] = Field(nullable=True, max_length=255, description="预计成交季度")
    # expected_service_duration_months: Optional[int] = Field(nullable=True, description="预计服务时长（月）")
    # expected_service_start_date: Optional[str] = Field(nullable=True, max_length=255, description="预计服务开始日期")
    # expected_upload_date: Optional[str] = Field(nullable=True, max_length=255, description="预计上传日期")
    # license_amount: Optional[int] = Field(nullable=True, description="License 金额")
    # ma_amount: Optional[int] = Field(nullable=True, description="MA 金额")
    # product_subscription_amount: Optional[int] = Field(nullable=True, description="产品订阅金额")
    # service_days_amount: Optional[int] = Field(nullable=True, description="人天服务金额")
    # cash_in_amount: Optional[float] = Field(nullable=True, description="Cash in 金额")
    # cash_in_date: Optional[str] = Field(nullable=True, max_length=255, description="Cash in 时间")
    # cash_in_quarter: Optional[str] = Field(nullable=True, max_length=255, description="Cash in 季度")
    opportunity_type: Optional[str] = Field(nullable=True, max_length=255, description="商机类型")
    # bidding_method: Optional[str] = Field(nullable=True, max_length=255, description="招标方式")
    signing_type: Optional[str] = Field(nullable=True, max_length=255, description="签约类型")
    # contract_signing_status: Optional[str] = Field(nullable=True, max_length=255, description="合同签署状态")
    general_agent: Optional[str] = Field(nullable=True, max_length=255, description="总代理")
    # distributor_id: Optional[str] = Field(nullable=True, max_length=255, description="经销商_唯一性ID")
    # distributor: Optional[str] = Field(nullable=True, max_length=255, description="经销商")
    # alternative_distributor_id: Optional[str] = Field(nullable=True, max_length=255, description="经销商备选_唯一性ID")
    # alternative_distributor: Optional[str] = Field(nullable=True, max_length=255, description="经销商备选")
    # application_developer: Optional[str] = Field(nullable=True, max_length=255, description="应用软件开发商")
    # cloud_vendor_id: Optional[str] = Field(nullable=True, max_length=255, description="Cloud 厂商_唯一性ID")
    # cloud_vendor: Optional[str] = Field(nullable=True, max_length=255, description="Cloud 厂商")
    # partner_cooperation_mode: Optional[str] = Field(nullable=True, max_length=255, description="合作伙伴的合作模式")
    presales_owner: Optional[str] = Field(nullable=True, max_length=255, description="售前负责人")
    # customer_industry: Optional[str] = Field(nullable=True, max_length=255, description="客户行业")
    # fy24_service_duration_months: Optional[int] = Field(nullable=True, description="FY24 服务时长（月）")
    # expected_upload_quarter: Optional[str] = Field(nullable=True, max_length=255, description="预计上传季度")
    # estimated_product_amount_total: Optional[float] = Field(nullable=True, description="预估产品金额之和")
    # estimated_fy24_license_revenue: Optional[float] = Field(nullable=True, description="预估 FY24 License Rev. 金额（不含税）")
    # estimated_fy24_subscription_revenue: Optional[float] = Field(nullable=True, description="预估 FY24 Subscription 收入金额（不含税）")
    # estimated_fy24_ma_revenue: Optional[float] = Field(nullable=True, description="预估 FY24 MA 收入金额（不含税）")
    # estimated_fy24_ps_revenue: Optional[float] = Field(nullable=True, description="预估 FY24 PS 收入金额（不含税）")
    # estimated_fy24_revenue_calculated: Optional[float] = Field(nullable=True, description="预估 FY24 收入金额-计算")
    # opportunity_order_amount: Optional[float] = Field(nullable=True, description="商机下单金额（预估 TCV 后台计算）")
    opportunity_source: Optional[str] = Field(nullable=True, max_length=255, description="商机来源")
    # sales_process: Optional[str] = Field(nullable=True, max_length=255, description="销售流程（必填）")
    # opportunity_number_identifier: Optional[str] = Field(nullable=True, max_length=255, description="商机编号标识")
    # opportunity_number: Optional[str] = Field(nullable=True, max_length=255, description="商机编号")
    # estimated_service_start_date_calculated: Optional[str] = Field(nullable=True, max_length=255, description="预估服务开始日期-计算")
    # ma_percentage: Optional[float] = Field(nullable=True, description="MA 所占比例（%）")
    # revenue_forecast_count: Optional[int] = Field(nullable=True, description="【纷享】收入预测条数")
    # opportunity_product_count: Optional[int] = Field(nullable=True, description="【纷享】商机产品条数")
    # total_revenue_forecast_incl_tax: Optional[float] = Field(nullable=True, description="收入预测金额合计（含税）")
    # ma_product_count: Optional[int] = Field(nullable=True, description="MA 产品条数")
    # license_product_count: Optional[int] = Field(nullable=True, description="License 产品条数")
    # subscription_product_count: Optional[int] = Field(nullable=True, description="订阅 产品条数")
    # service_days_product_count: Optional[int] = Field(nullable=True, description="人天 产品条数")
    ppl_product_type: Optional[str] = Field(nullable=True, max_length=255, description="PPL 产品类型")
    # mysql_family_capture: Optional[str] = Field(nullable=True, max_length=255, description="MySQL Family Capture")
    # is_special_license_sale: Optional[str] = Field(nullable=True, max_length=255, description="是否特殊申请出售 license")
    # special_license_sale_number: Optional[str] = Field(nullable=True, max_length=255, description="特殊申请出售 license 编号")
    # key_project_label: Optional[str] = Field(nullable=True, max_length=255, description="重点项目 Label")
    # partner_id: Optional[str] = Field(nullable=True, max_length=255, description="合作伙伴_唯一性ID")
    # partner: Optional[str] = Field(nullable=True, max_length=255, description="合作伙伴")
    # external_source: Optional[str] = Field(nullable=True, max_length=255, description="外部来源")
    latest_followup_date_new: Optional[str] = Field(nullable=True, max_length=255, description="最近跟进日期-新")
    # daily_record_count: Optional[int] = Field(nullable=True, description="日常记录条数")
    # has_customer_advocacy: Optional[str] = Field(nullable=True, max_length=255, description="是否会有客户站台/文章/社区联动")
    # industry_lighthouse_project: Optional[str] = Field(nullable=True, max_length=255, description="行业 lighthouse 项目")
    remarks: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="备注说明")
    # internal_process_latest_progress: Optional[str] = Field(nullable=True, max_length=255, description="内部流程 最新进展")
    # timeline_project_progress: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="倒排时间表项目进展")
    # countdown_next_plan: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="Count down下一步计划")
    # countdown_bottleneck: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="问题卡点（count down）")
    # operational_risk_assessment: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="运营判断风险")
    # owner_industry: Optional[str] = Field(nullable=True, max_length=255, description="负责人所属行业")
    # regular_member_readonly: Optional[str] = Field(nullable=True, max_length=255, description="普通成员-只读")
    # regular_member_readwrite: Optional[str] = Field(nullable=True, max_length=255, description="普通成员-读写")
    # joint_follower_readonly: Optional[str] = Field(nullable=True, max_length=255, description="联合跟进人-只读")
    # joint_follower_readwrite: Optional[str] = Field(nullable=True, max_length=255, description="联合跟进人-读写")
    # aftersales_readonly: Optional[str] = Field(nullable=True, max_length=255, description="售后人员-只读")
    # aftersales_readwrite: Optional[str] = Field(nullable=True, max_length=255, description="售后人员-读写")
    # has_isv_joint_solution: Optional[str] = Field(nullable=True, max_length=255, description="是否包含 ISV 联合解决方案")
    # estimated_solution_1_percentage: Optional[float] = Field(nullable=True, description="预估联合解决方案-1 占比（节点数或vCPU数）（%）")
    # solution_1_number_id: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案名称编号-1_唯一性ID")
    # solution_1_number: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案名称编号-1")
    # solution_1_certified_partner: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案1认证合作伙伴名称")
    # solution_1_name: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案名称-1")
    # estimated_solution_2_percentage: Optional[float] = Field(nullable=True, description="预估联合解决方案-2 占比（节点数或vCPU数）（%）")
    # solution_2_certified_partner: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案2认证合作伙伴名称")
    # solution_2_number_id: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案名称编号-2_唯一性ID")
    # solution_2_number: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案名称编号-2")
    # solution_2_name: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案名称-2")
    # mutual_certified_solution_partner: Optional[str] = Field(nullable=True, max_length=255, description="联合解决方案互认证合作伙伴")
    # mutual_certified_solution_percentage: Optional[float] = Field(nullable=True, description="互认证联合解决方案所占比例（%）")
    # is_channel_filing_opportunity: Optional[str] = Field(nullable=True, max_length=255, description="是否渠道报备商机")
    # partner_opportunity_filing_unique_id: Optional[str] = Field(nullable=True, max_length=255, description="合作伙伴商机报备ID_唯一性ID")
    # partner_opportunity_filing_id: Optional[str] = Field(nullable=True, max_length=255, description="合作伙伴商机报备ID")
    # filing_partner_name: Optional[str] = Field(nullable=True, max_length=255, description="报备合作伙伴名称")
    # partner_filing_opportunity_owner: Optional[str] = Field(nullable=True, max_length=255, description="合作伙伴报备商机负责人")
    # competitor_advantages: Optional[str] = Field(nullable=True, max_length=255, description="友商优势因素")
    quotation_status: Optional[str] = Field(nullable=True, max_length=255, description="报价单状态")
    # order_status: Optional[str] = Field(nullable=True, max_length=255, description="订单状态")
    # project_approval: Optional[str] = Field(nullable=True, max_length=255, description="立项批复")
    # has_poc: Optional[str] = Field(nullable=True, max_length=255, description="是否进行PoC")
    # has_bid: Optional[str] = Field(nullable=True, max_length=255, description="是否投标")
    # bid_result: Optional[str] = Field(nullable=True, max_length=255, description="中标结果")
    # creator: Optional[str] = Field(nullable=True, max_length=255, description="创建人")
    # main_lead_id: Optional[str] = Field(nullable=True, max_length=255, description="主线索_唯一性ID")
    # main_lead: Optional[str] = Field(nullable=True, max_length=255, description="主线索")
    # loss_reason: Optional[str] = Field(nullable=True, max_length=255, description="输单原因")
    create_time: Optional[str] = Field(nullable=True, max_length=255, description="创建时间")
    last_modifier: Optional[str] = Field(nullable=True, max_length=255, description="最后修改人")
    opportunity_stage: Optional[str] = Field(nullable=True, max_length=255, description="商机阶段（必填）")
    stage_status: Optional[str] = Field(nullable=True, max_length=255, description="阶段状态")
    stage_change_time: Optional[str] = Field(nullable=True, max_length=255, description="阶段变更时间")
    last_modified_time: Optional[datetime] = Field(nullable=True, description="最后修改时间")
    business_type: Optional[str] = Field(nullable=True, max_length=255, description="业务类型（必填）")
    last_followup_time: Optional[str] = Field(nullable=True, max_length=255, description="最后跟进时间")
    owner_main_department: Optional[str] = Field(nullable=True, max_length=255, description="负责人主属部门")

    # New fields
    weekly_update: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="Weekly Update")
    sl_pull_in: Optional[str] = Field(nullable=True, max_length=255, description="SL Pull IN")
    lost_reason: Optional[str] = Field(nullable=True, max_length=255, description="丢标原因")
    bidding_time: Optional[str] = Field(nullable=True, max_length=255, description="招标时间")
    renew_risk_level: Optional[str] = Field(nullable=True, max_length=255, description="Renew 风险度")
    customer_category: Optional[str] = Field(nullable=True, max_length=255, description="客户分类")
    quotation_order_status: Optional[str] = Field(nullable=True, max_length=255, description="报价/下单状态")
    source: Optional[str] = Field(nullable=True, max_length=255, description="来源")
    project_contribution: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="立项贡献（立项报告的内容）")
    project_date: Optional[str] = Field(nullable=True, max_length=255, description="立项日期")
    budget_approval_status: Optional[str] = Field(nullable=True, max_length=255, description="预算审批是否完成")
    sales_order_archive_status: Optional[str] = Field(nullable=True, max_length=255, description="销售订单归档状态")
    is_channel_reported_opportunity: str = Field(max_length=255, description="是否渠道报备商机（必填）")
    is_project_approved: Optional[str] = Field(nullable=True, max_length=255, description="是否立项")

    # New OPS CD and KD fields
    ops_cd_project_retrospective_schedule: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="ops cd 项目进展倒排时间表")
    ops_cd_critical_issues: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="ops cd 重大问题卡点")
    ops_cd_business_progress: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="ops cd 商务进展")
    kd_closure_milestone: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="KD-关单节点")
    kd_decision_chain: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="KD-决策链条")
    kd_competitor_strategy: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="KD-友商策略和动态")
    kd_breakthrough_basis: Optional[str] = Field(sa_column=Column(Text, nullable=True), description="KD-突破单依据")

    __tablename__ = "crm_opportunities"
    
    account: Optional["CRMAccount"] = Relationship(
        sa_relationship_kwargs={
            "primaryjoin": "and_(CRMOpportunity.customer_id==CRMAccount.unique_id)",
            "foreign_keys": "[CRMOpportunity.customer_id]",
            "viewonly": True
        }
    )