"""add_crm_kg_status_columns

Revision ID: 088e5cd3d91d
Revises: b034a92a03be
Create Date: 2025-03-25 10:08:08.466016

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = '088e5cd3d91d'
down_revision = 'b034a92a03be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('crm_index_status', sa.Enum('NOT_STARTED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='playbookkgindexstatus'), nullable=False))
    op.add_column('chunks', sa.Column('crm_index_result', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'crm_index_result')
    op.drop_column('chunks', 'crm_index_status')
    # ### end Alembic commands ###
