"""playbook kg

Revision ID: 313b78f69ef0
Revises: a54f966436ce
Create Date: 2025-01-21 10:20:40.539541

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = '313b78f69ef0'
down_revision = 'a54f966436ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('playbook_index_status', sa.Enum('NOT_STARTED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='playbookkgindexstatus'), nullable=False))
    op.add_column('chunks', sa.Column('playbook_index_result', sa.Text(), nullable=True))
    op.add_column('uploads', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'meta')
    op.drop_column('chunks', 'playbook_index_result')
    op.drop_column('chunks', 'playbook_index_status')
    # ### end Alembic commands ###
