"""playbook kg

Revision ID: 313b78f69ef0
Revises: a54f966436ce
Create Date: 2025-01-21 10:20:40.539541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313b78f69ef0'
down_revision = 'a54f966436ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('playbook_index_status', sa.Enum('NOT_STARTED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='playbookkgindexstatus'), nullable=False))
    op.add_column('chunks', sa.Column('playbook_index_result', sa.Text(), nullable=True))
    op.add_column('uploads', sa.Column('meta', sa.JSON(), nullable=True))

    graph_type_enum = sa.Enum('general', 'playbook', name='graphtype')
    
    op.add_column('entities', sa.Column('graph_type', 
        graph_type_enum,
        nullable=False,
        server_default='general'
    ))
    
    op.add_column('relationships', sa.Column('graph_type',
        graph_type_enum,
        nullable=False,
        server_default='general'
    ))
    
    op.create_index('idx_entity_graph_type', 'entities', ['graph_type'])
    op.create_index('idx_relationship_graph_type', 'relationships', ['graph_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_relationship_graph_type', table_name='relationships')
    op.drop_index('idx_entity_graph_type', table_name='entities')
    
    op.drop_column('relationships', 'graph_type')
    op.drop_column('entities', 'graph_type')
    
    sa.Enum(name='graphtype').drop(op.get_bind(), checkfirst=True)
        
    op.drop_column('uploads', 'meta')
    op.drop_column('chunks', 'playbook_index_result')
    op.drop_column('chunks', 'playbook_index_status')
    # ### end Alembic commands ###
