"""create_customer_documents_table

Revision ID: 35d3b2fe795f
Revises: 4e3d779a4137
Create Date: 2025-08-12 11:15:56.658496

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = '35d3b2fe795f'
down_revision = '4e3d779a4137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_documents',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, comment='自增主键ID'),
        sa.Column('file_category', sa.String(length=255), nullable=False, comment='文件类别，如ABP、CallHigh等'),
        sa.Column('account_name', sa.String(length=255), nullable=False, comment='客户名称'),
        sa.Column('account_id', sa.String(length=255), nullable=False, comment='客户ID'),
        sa.Column('document_url', sa.Text(), nullable=False, comment='文档链接'),
        sa.Column('document_type', sa.String(length=255), nullable=True, comment='文档类型'),
        sa.Column('document_title', sa.String(length=500), nullable=True, comment='文档标题'),
        sa.Column('uploader_id', sqlmodel.sql.sqltypes.GUID(), nullable=False, comment='上传者ID'),
        sa.Column('uploader_name', sa.String(length=255), nullable=False, comment='上传者姓名'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
        sa.Column('document_content_id', sa.Integer(), nullable=True, comment='关联的文档内容ID'),
        sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['document_content_id'], ['document_contents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    
    # Create foreign key constraint for uploader_id
    op.create_foreign_key(
        'fk_customer_documents_uploader_id',
        'customer_documents',
        'users',
        ['uploader_id'],
        ['id']
    )
    
    # Create foreign key constraint for document_content_id
    op.create_foreign_key(
        'fk_customer_documents_document_content_id',
        'customer_documents',
        'document_contents',
        ['document_content_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_customer_documents_document_content_id', 'customer_documents', type_='foreignkey')
    op.drop_constraint('fk_customer_documents_uploader_id', 'customer_documents', type_='foreignkey')
    op.drop_table('customer_documents')
    # ### end Alembic commands ###

