"""create_user_profiles_table

Revision ID: 4e3d779a4137
Revises: d1776949f5f5
Create Date: 2025-08-08 10:08:54.261341

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = '4e3d779a4137'
down_revision = 'd1776949f5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建用户档案表
    op.create_table('user_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column('oauth_user_id', sa.String(length=255), nullable=True),
        sa.Column('feishu_open_id', sa.String(length=255), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('department', sa.String(length=255), nullable=True),
        sa.Column('position', sa.String(length=255), nullable=True),
        sa.Column('direct_manager_id', sa.String(length=255), nullable=True),
        sa.Column('direct_manager_name', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    )
    
    # 创建索引
    op.create_index(
        "idx_user_profiles_department_is_active",
        "user_profiles",
        ["department", "is_active"],
        unique=False,
    )
    op.create_index(
        "idx_user_profiles_direct_manager_id_is_active",
        "user_profiles",
        ["direct_manager_id", "is_active"],
        unique=False,
    )
    
    op.create_index(op.f('ix_user_profiles_oauth_user_id'), 'user_profiles', ['oauth_user_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除索引
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_oauth_user_id'), table_name='user_profiles')
    op.drop_index("idx_user_profiles_department_is_active", table_name="user_profiles")
    op.drop_index("idx_user_profiles_direct_manager_id_is_active", table_name="user_profiles")
    
    # 删除表
    op.drop_table('user_profiles')
    
    # ### end Alembic commands ###
