"""add_is_call_high_to_crm_sales_visit_records

Revision ID: 9ff94839d3eb
Revises: 35d3b2fe795f
Create Date: 2025-08-12 14:57:00.651875

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = '9ff94839d3eb'
down_revision = '35d3b2fe795f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_sales_visit_records', sa.Column('is_call_high', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_sales_visit_records', 'is_call_high')
    # ### end Alembic commands ###
