"""extend_graph_type_enum

Revision ID: b034a92a03be
Revises: 211f3c5aa125
Create Date: 2025-03-25 10:03:34.154957

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType

# revision identifiers, used by Alembic.
revision = 'b034a92a03be'
down_revision = '211f3c5aa125'
branch_labels = None
depends_on = None

# new Enum
new_enum = sa.Enum('general', 'playbook', 'crm', name='graphtype')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE entities MODIFY COLUMN graph_type ENUM('general', 'playbook', 'crm') NOT NULL DEFAULT 'general'")
    op.execute("ALTER TABLE relationships MODIFY COLUMN graph_type ENUM('general', 'playbook', 'crm') NOT NULL DEFAULT 'general'")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # this will lose 'crm' type data, so first convert it to 'general'
    op.execute("UPDATE entities SET graph_type = 'general' WHERE graph_type = 'crm'")
    op.execute("UPDATE relationships SET graph_type = 'general' WHERE graph_type = 'crm'")
    
    # restore to original enum type
    op.execute("ALTER TABLE entities MODIFY COLUMN graph_type ENUM('general', 'playbook') NOT NULL DEFAULT 'general'")
    op.execute("ALTER TABLE relationships MODIFY COLUMN graph_type ENUM('general', 'playbook') NOT NULL DEFAULT 'general'")
    # ### end Alembic commands ###