website:
  title:
    default: "APTSell"
    data_type: str
    description: "The title of the website."
    client: true
  description:
    default: "Sales Intelligent Assistant (Sia)"
    data_type: str
    description: "The description of the website."
    client: true
  homepage_title:
    default: "Ask me Anything"
    data_type: str
    description: "The title of the homepage."
    client: true
  homepage_example_questions:
    default:
      - "你是谁"
      - "你能做什么"
      - "你是个知识库吗"
    data_type: list
    description: "The example questions on the homepage."
    client: true
  homepage_footer_links:
    default:
      - text: "Release Notes"
        href: "https://zhizhenzhihe.com"
      - text: "© 2025 APTSell"
        href: "https://zhizhenzhihe.com"
    data_type: list
    description: "The footer links on the homepage."
    client: true
  logo_in_dark_mode:
    default: "https://media.murmured.me/images/aptsell_dark.svg"
    data_type: str
    description: "The logo in dark mode."
    client: true
  logo_in_light_mode:
    default: "https://media.murmured.me/images/aptsell_dark.svg"
    data_type: str
    description: "The logo in light mode."
    client: true
  social_github:
    default: "https://github.com/pingcap/tidb.ai"
    data_type: str
    description: "The link to the github"
    client: true
  social_twitter:
    default: "https://twitter.com/PingCAP"
    data_type: str
    description: "The link to the twitter"
    client: true
  social_discord:
    default: "https://discord.gg/XzSW23Jg9p"
    data_type: str
    description: "The link to the discord"
    client: true
  ga_id:
    default: ""
    data_type: str
    description: "Google Analytics ID"
    client: true

custom_js:
  custom_js_example_questions:
    default:
      - "你是谁"
      - "你能做什么"
      - "你是个知识库吗"
    data_type: list
    description: "The example questions on the custom_js."
    client: true
  custom_js_button_label:
    default: "Ask me Anything"
    data_type: str
    description: "The button label on the custom_js."
    client: true
  custom_js_button_img_src:
    default: "https://media.murmured.me/images/aptsell_dark.svg"
    data_type: str
    description: "The button image on the custom_js."
    client: true
  custom_js_logo_src:
    default: "https://media.murmured.me/images/aptsell_dark.svg"
    data_type: str
    description: "The logo on the custom_js."
    client: true

chat:
  langfuse_secret_key:
    default: ""
    data_type: str
    description: "The secret key of Langfuse."
    client: false
  langfuse_public_key:
    default: ""
    data_type: str
    description: "The public key of Langfuse."
    client: false
  langfuse_host:
    default: "https://us.cloud.langfuse.com"
    data_type: str
    description: "The host of Langfuse."
    client: false
  enable_post_verifications:
    default: true
    data_type: bool
    description: "Enable post verification for all chats."
    client: true
  enable_post_verifications_for_widgets:
    default: false
    data_type: bool
    description: "Enable post verification for chats from js widgets."
    client: true

upload:
  max_upload_file_size:
    default: 104857600    # 100 MiB
    data_type: int
    description: "Max body size (in bytes) of upload file."
    client: true